### ISSUE TITLE
It can be used in Windows?

### ISSUE THREAD

**Issue by navakelvin** [rareitems/anki.nvim#5]
I have tried using it dead-end on Windows under powershell.

I get the error that libcurl is not supported. Even after updating to the latest version of curl with Chocolatey.

**Comment by rareitems** [comment]
The way I use curl is via [plenary](https://github.com/nvim-lua/plenary.nvim) and it looks they have support for curl on Windows (https://github.com/nvim-lua/plenary.nvim/pull/527). Are you running the latest version of plenary? (the changed that added support for Windows was merged in January so probably that's not the issue)

Can you show the whole error? It looks like Windows has some problems (which were supposedly fix in plenary) with sending compressed requests (https://github.com/nvim-lua/plenary.nvim/issues/176) but without the error can't tell if that's the issue.

**Comment by navakelvin** [comment]
I was able to get it working by updating Neovim.
